// Code generated by goctl. DO NOT EDIT.
// Source: myservice.proto

package server

import (
	"demo-go/streamRequsetZeroSample/internal/logic"
	"demo-go/streamRequsetZeroSample/internal/svc"
	"demo-go/streamRequsetZeroSample/types/myapp/myservice"
)

type MyServiceServer struct {
	svcCtx *svc.ServiceContext
	myservice.UnimplementedMyServiceServer
}

func NewMyServiceServer(svcCtx *svc.ServiceContext) *MyServiceServer {
	return &MyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MyServiceServer) StreamRequests(stream myservice.MyService_StreamRequestsServer) error {
	l := logic.NewStreamRequestsLogic(stream.Context(), s.svcCtx)
	return l.StreamRequests(stream)
}
