// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: myservice.proto

package myservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MyService_StreamRequests_FullMethodName = "/myservice.MyService/StreamRequests"
)

// MyServiceClient is the client API for MyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MyServiceClient interface {
	StreamRequests(ctx context.Context, opts ...grpc.CallOption) (MyService_StreamRequestsClient, error)
}

type myServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMyServiceClient(cc grpc.ClientConnInterface) MyServiceClient {
	return &myServiceClient{cc}
}

func (c *myServiceClient) StreamRequests(ctx context.Context, opts ...grpc.CallOption) (MyService_StreamRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &MyService_ServiceDesc.Streams[0], MyService_StreamRequests_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &myServiceStreamRequestsClient{stream}
	return x, nil
}

type MyService_StreamRequestsClient interface {
	Send(*MyRequest) error
	Recv() (*MyResponse, error)
	grpc.ClientStream
}

type myServiceStreamRequestsClient struct {
	grpc.ClientStream
}

func (x *myServiceStreamRequestsClient) Send(m *MyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *myServiceStreamRequestsClient) Recv() (*MyResponse, error) {
	m := new(MyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyServiceServer is the server API for MyService service.
// All implementations must embed UnimplementedMyServiceServer
// for forward compatibility
type MyServiceServer interface {
	StreamRequests(MyService_StreamRequestsServer) error
	mustEmbedUnimplementedMyServiceServer()
}

// UnimplementedMyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMyServiceServer struct {
}

func (UnimplementedMyServiceServer) StreamRequests(MyService_StreamRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRequests not implemented")
}
func (UnimplementedMyServiceServer) mustEmbedUnimplementedMyServiceServer() {}

// UnsafeMyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MyServiceServer will
// result in compilation errors.
type UnsafeMyServiceServer interface {
	mustEmbedUnimplementedMyServiceServer()
}

func RegisterMyServiceServer(s grpc.ServiceRegistrar, srv MyServiceServer) {
	s.RegisterService(&MyService_ServiceDesc, srv)
}

func _MyService_StreamRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MyServiceServer).StreamRequests(&myServiceStreamRequestsServer{stream})
}

type MyService_StreamRequestsServer interface {
	Send(*MyResponse) error
	Recv() (*MyRequest, error)
	grpc.ServerStream
}

type myServiceStreamRequestsServer struct {
	grpc.ServerStream
}

func (x *myServiceStreamRequestsServer) Send(m *MyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *myServiceStreamRequestsServer) Recv() (*MyRequest, error) {
	m := new(MyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MyService_ServiceDesc is the grpc.ServiceDesc for MyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myservice.MyService",
	HandlerType: (*MyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRequests",
			Handler:       _MyService_StreamRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "myservice.proto",
}
